### ISSUE TITLE
tar_extract not working with tar 2.1.1

### ISSUE THREAD

**Issue by chris-gillatt** [chef-cookbooks/tar#48]
### Cookbook version
[2.1.1]

### Chef-client version
[12.5.1]

### Platform Details
[CentOS Linux release 7.2.1511]

### Scenario:
[Attempting to untar a local file using tar_extract resource]

### Steps to Reproduce:
1) include resource in metadata

2) add something to foo::recipe:
```
tar_extract '/sometar.tar.gz' do
  action :extract_local
  target_dir '/some/location'
  creates '/some/location/file'
end
```

### Expected Result:
tarball unpacked to target directory.

### Actual Result:
`ERROR: tar_extract[/sometar.tar.gz] (foo::recipe line 90) had an error: NoMethodError: No resource or method named `extract_tar' for `LWRP resource tar_extract from cookbook tar action provider "/sometar.tar.gz"'`

Appears that "tar_extract" switches to "extract_tar" somewhere in the code.

To resolve, I've pinned 'tar', '= 2.0.0' which works fine for my environment.  Could my Chef Client version be too old for tar version 2.1.1, or is a fix required?

**Comment by iennae** [comment]
Cookbook version 2.1.1 minimum Chef version required is Chef 12.7 due to some incompatible changes in later Chef 12 versions. If you wanted to use a locally modified version of 2.1.1, you could update the extract resource (https://github.com/chef-cookbooks/tar/blob/91349e2bbb6f84535dba4ead26e3c3af90272251/resources/extract.rb) at https://github.com/chef-cookbooks/tar/blob/91349e2bbb6f84535dba4ead26e3c3af90272251/resources/extract.rb#L81 to add .class_eval to the end of action_class as can be seen here https://github.com/chef-cookbooks/tar/commit/91349e2bbb6f84535dba4ead26e3c3af90272251#diff-843d8e62c91093bb35e0517d106411dc. Alternatively, I would recommend to update your chef_client to minimally 12.7 as all of the Chef supported community cookbooks will be moving towards minimally 12.7 if they haven't already done so.
